server.port: 8443
#server.ssl.client-auth: NEED
server.ssl.bundle: server
spring.profiles.active: dev

---
spring.config.activate.on-profile: dev
spring.ssl.bundle.jks:
  server:
    reload-on-update: true
    keystore:
      location: classpath:keystore.jks
      password: 123456
      type: JKS
    truststore:
      location: classpath:truststore.jks
      password: 123456
      type: JKS
---
spring.config.activate.on-profile: prod
spring.ssl.bundle.pem:
  server:
    keystore:
      certificate: ${CERT_PATH}/tls.crt
      private-key: ${CERT_PATH}/tls.key